# Generated by Django 2.2 on 2021-04-28 13:28

from decimal import Decimal
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=256, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, db_index=True, default='', max_length=128, verbose_name='артикул')),
                ('name', models.CharField(default='', max_length=256, verbose_name='имя')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='цена')),
                ('description', models.TextField(blank=True, default='', verbose_name='описание')),
                ('status', models.CharField(blank=True, choices=[('processing', 'Информация о товаре добавляется в систему'), ('moderating', 'Товар проходит модерацию'), ('processed', 'Информация обновлена'), ('failed_moderation', 'Товар не прошел модерацию'), ('failed_validation', 'Товар не прошел валидацию'), ('failed', 'Возникла ошибка'), ('archived', 'Архивировано')], default='', max_length=32)),
                ('ozon_fbs_sku', models.CharField(blank=True, default='', max_length=128)),
                ('ozon_fbo_sku', models.CharField(blank=True, default='', max_length=128)),
                ('ozon_product_id', models.PositiveIntegerField(blank=True, default=0)),
                ('ozon_category_id', models.PositiveIntegerField(blank=True, default=0)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=256, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(default='', max_length=256, verbose_name='name')),
                ('opening_date', models.DateField(null=True, verbose_name='дата открытия')),
                ('last_download_products', models.DateTimeField(blank=True, null=True)),
                ('last_download_ozon_fbo_postings', models.DateTimeField(blank=True, null=True)),
                ('last_download_ozon_fbs_postings', models.DateTimeField(blank=True, null=True)),
                ('last_update_ozon_orders', models.DateTimeField(blank=True, null=True)),
                ('disabled_reason', models.CharField(blank=True, choices=[('connect_failed_ozon_api', 'Не удалось подключится к Ozon Seller API. Проверьте Client ID и API Key.')], default='', max_length=256, verbose_name='причина отключения')),
            ],
            options={
                'verbose_name': 'магазин',
                'verbose_name_plural': 'магазины',
                'ordering': ('-id',),
            },
        ),
    ]
