# Generated by Django 2.2 on 2021-04-28 13:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import wb.models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='raw_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=wb.models.raw_data_default),
        ),
        migrations.CreateModel(
            name='ProductCardImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_file_url', models.CharField(blank=True, default='', max_length=256)),
                ('product_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wb.ProductCard')),
            ],
        ),
        migrations.AddIndex(
            model_name='productcardimage',
            index=models.Index(fields=['remote_file_url'], name='wb_productc_remote__b78504_idx'),
        ),
    ]
