# Generated by Django 2.2 on 2021-04-28 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0003_productcard_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wb.ProductCardImage'),
        ),
    ]
