# Generated by Django 2.2 on 2021-04-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0004_productcard_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcard',
            old_name='ozon_category_id',
            new_name='fbw_category_id',
        ),
        migrations.RenameField(
            model_name='productcard',
            old_name='ozon_fbo_sku',
            new_name='fbw_fbo_sku',
        ),
        migrations.RenameField(
            model_name='productcard',
            old_name='ozon_fbs_sku',
            new_name='fbw_fbs_sku',
        ),
        migrations.RenameField(
            model_name='productcard',
            old_name='ozon_product_id',
            new_name='fbw_product_id',
        ),
    ]
