# Generated by Django 2.2 on 2021-04-28 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0005_auto_20210428_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcard',
            old_name='fbw_category_id',
            new_name='wb_category_id',
        ),
        migrations.RenameField(
            model_name='productcard',
            old_name='fbw_fbo_sku',
            new_name='wb_fbs_sku',
        ),
        migrations.RenameField(
            model_name='productcard',
            old_name='fbw_fbs_sku',
            new_name='wb_fbw_sku',
        ),
        migrations.RenameField(
            model_name='productcard',
            old_name='fbw_product_id',
            new_name='wb_product_id',
        ),
    ]
