# Generated by Django 2.2 on 2021-04-28 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0006_auto_20210428_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='status',
        ),
        migrations.RemoveField(
            model_name='productcard',
            name='wb_fbs_sku',
        ),
        migrations.RemoveField(
            model_name='productcard',
            name='wb_fbw_sku',
        ),
    ]
