# Generated by Django 2.2 on 2021-04-28 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0007_auto_20210428_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcard',
            name='moderated_at',
        ),
    ]
