# Generated by Django 2.2 on 2021-04-29 13:22

from decimal import Decimal
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import wb.models


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0008_remove_productcard_moderated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, db_index=True, default='', editable=False, max_length=256, verbose_name='идентификатор')),
                ('created_at', models.DateTimeField(null=True, verbose_name='дата и время')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='дата и время обновления')),
                ('in_process_at', models.DateTimeField(null=True, verbose_name='принят в обработку')),
                ('number', models.CharField(db_index=True, default='', max_length=64, verbose_name='номер')),
                ('posting_type', models.CharField(choices=[('ozon_fbo', 'Ozon FBO'), ('ozon_fbs', 'Ozon FBS')], default='', max_length=32, verbose_name='тип отправления')),
                ('posting_number', models.CharField(db_index=True, default='', max_length=64, verbose_name='номер отправления')),
                ('status', models.CharField(choices=[('awaiting_approve', 'Ожидает подтверждения'), ('awaiting_packaging', 'Ожидает упаковки'), ('awaiting_deliver', 'Ожидает отгрузки'), ('delivering', 'Доставляется'), ('delivered', 'Доставлено'), ('cancelled', 'Аннулировано'), ('not_accepted', 'Не принят в сортировочном центре')], default='', max_length=32, verbose_name='статус')),
                ('fixed_expenses_of_store', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='фиксированные расходы магазина')),
                ('other_expenses_of_store', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='прочие расходы магазина')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='wb.Store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(null=True, verbose_name='дата и время обновления')),
                ('quantity', models.IntegerField(default=0, verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='цена')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=12, null=True, verbose_name='закупочная цена')),
                ('product_total_cost', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=12, null=True, verbose_name='себестоимость товара')),
                ('product_reject_rate', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='процент брака')),
                ('product_return_rate', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, verbose_name='процент возврата товара')),
                ('packing_cost', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='стоимость упаковки')),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='стоимость доставки')),
                ('return_cost', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='стоимость возврата')),
                ('commission', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='комиссия')),
                ('ozon_fbs_sku', models.CharField(blank=True, default='', max_length=128)),
                ('ozon_fbo_sku', models.CharField(blank=True, default='', max_length=128)),
                ('raw_product_data', django.contrib.postgres.fields.jsonb.JSONField(default=wb.models.raw_data_default)),
                ('raw_financial_data', django.contrib.postgres.fields.jsonb.JSONField(default=wb.models.raw_data_default)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wb.Order')),
                ('product_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='wb.ProductCard')),
            ],
        ),
    ]
