# Generated by Django 2.2 on 2021-04-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wb', '0009_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='ozon_fbo_sku',
            new_name='wb_fbs_sku',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ozon_fbs_sku',
        ),
    ]
